In [1]:
import os
import os.path
import shutil
import sys
import glob
from os import remove
from shutil import rmtree

import pandas as pd # cargamos la libreria pandas

In [4]:
source = ''
destination = ''
# source = 'C:\Users\Ericsson\Downloads\DESCARGA RUBER'
# destination = 'C:\Users\Ericsson\Downloads\DESCARGA RUBER/practica'
carpt = 0
while not os.path.exists(source):
    source = input('Enter a valid source directory\n')
while not os.path.exists(destination):
    destination = input('Enter a valid destination directory\n')

Enter a valid source directory
C:\Users\Ericsson\Downloads\DESCARGA RUBER
Enter a valid destination directory
C:\Users\Ericsson\Downloads\DESCARGA RUBER/practica

In [73]:
print(source)
print(destination)
carpt = 0
for root, dirs, files in os.walk(source, topdown=False):
    for file in files: 
        extension = os.path.splitext(file)[0][0:5].upper()
        #print(file) 
        if extension == "MP_EX":
            print(file)
            df = pd.read_excel(os.path.join(root,file), sheet_name='TANQUE', usecols="A:P", header=4)
            print(df.shape)
           # ruta = '"'+ os.path.join(root,file).upper()+ '"'
           
            #print(os.path.join(root,file))
            #df = pd.read_csv(ruta, decimal='.', encoding='utf-8', header=0)
            #df.shape
            carpt +=   1
        
        
    #rmtree(os.path.join(root))
    
print("PROCESO TERMINADO..OK  TOTAL CARPETAS: " + str(carpt ) )
df.head(17)

C:\Users\Ericsson\Downloads\DESCARGA RUBER
C:\Users\Ericsson\Downloads\DESCARGA RUBER/practica
MP_EX_ NECHI _5184618_CORREGIDO_2020.xlsx
(94, 16)
PROCESO TERMINADO..OK  TOTAL CARPETAS: 1

,TANQUES,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,SISTEMA DE ALMACENAMIENTO COMBUSTIBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIQUETE OT:,NaN,5184618,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PERIODICIDAD:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FECHA ULTIMA INSPECCION:,NaN,NaN,2019-08-30 00:00:00,NaN,NaN,NaN
3,FECHA:,2020-01-17 00:00:00,NaN,NaN,NaN,NaN,NaN,HORA INICIO:,NaN,09:30:00,HORA FINAL:,NaN,16:00:00:00 p. m.,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LOCALIDAD:,NECHI GD211,NaN,NaN,NaN,NaN,NaN
5,DATOS TECNICOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MODELO TANQUE,CANT ACPM,NaN,TIPO,NaN,NaN,DIMENSIONES (cm),NaN,NaN,NaN,ALARMA BAJO NIVEL ACPM,NaN,MEDICIÓN NIVEL ACPM,NaN,NaN,NaN
7,NaN,Cap\n(Gls),Existe\n(Gal),Cilindro Vert.,Cilindro Hori.,Cúbico,Diámetro,Alto,Ancho,Largo,EN SITIO (SI/NO),EN GESTIÓN (SI/NO),Visual,Análogo,Digital,NaN
8,Subase,120,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Reserva 1,250,250,1,NaN,NaN,NaN,NaN,NaN,NaN,OK,NaN,OK,NaN,NaN,NaN
10,Reserva 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Reserva 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,TOTAL,370,370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,INTERVENCION,NaN,NaN,LIMPIEZA,NaN,CAMBIO,NaN,OBSERVACIONES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CUERPO EXTERNO,NaN,NaN,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,MANGUERAS INDICADORAS DE NIVEL,NaN,NaN,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,INDICADORES DE NIVEL,NaN,NaN,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
df1 = df.fillna('')
df1

,TANQUES,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,SISTEMA DE ALMACENAMIENTO COMBUSTIBLE,,,,,,,,,,,TIQUETE OT:,,5184618,,
1,,,,,,,,,,,,,,,,
2,PERIODICIDAD:,,,,,,,,,FECHA ULTIMA INSPECCION:,,,2019-08-30 00:00:00,,,
3,FECHA:,2020-01-17 00:00:00,,,,,,HORA INICIO:,,09:30:00,HORA FINAL:,,16:00:00:00 p. m.,,,
4,,,,,,,,,,LOCALIDAD:,NECHI GD211,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,POR EL CONTRATISTA,,,,,,,,POR EL CONTRATISTA,,,,,,,
90,,,,,,,,,,,,,,,,
91,,,,,,,,,,,,,,,,
92,,,,,,,,,,,,,,,,
93,,,,,,,V2. 19/01/2017,,,,,,,,,

In [120]:
print(df['TANQUES'])

0     SISTEMA DE ALMACENAMIENTO COMBUSTIBLE
1                                       NaN
2                            PERIODICIDAD:
3                                    FECHA:
4                                       NaN
                      ...
89                       POR EL CONTRATISTA
90                                      NaN
91                                      NaN
92                                      NaN
93                                      NaN
Name: TANQUES, Length: 94, dtype: object

In [124]:
for i in df1.index:
    print(type(df['TANQUES'][i]))
    print((df['TANQUES'][i]))
    #if df['TANQUES'][i]) != '':

<class 'str'>
SISTEMA DE ALMACENAMIENTO COMBUSTIBLE
<class 'float'>
nan
<class 'str'>
PERIODICIDAD:
<class 'str'>
FECHA:
<class 'float'>
nan
<class 'str'>
DATOS TECNICOS
<class 'str'>
MODELO TANQUE
<class 'float'>
nan
<class 'str'>
Subase
<class 'str'>
Reserva 1
<class 'str'>
Reserva 2
<class 'str'>
Reserva 3
<class 'str'>
TOTAL
<class 'str'>
INTERVENCION
<class 'str'>
CUERPO EXTERNO
<class 'str'>
MANGUERAS INDICADORAS DE NIVEL
<class 'str'>
INDICADORES DE NIVEL
<class 'str'>
MANGUERAS DE ABASTECIMIENTO
<class 'str'>
FUGAS
<class 'str'>
LLAVES DE ABASTECIMINETO
<class 'str'>
FUGAS EN LAS LLAVES
<class 'str'>
ENTORNO FISICO
<class 'str'>
EXTINTOR
<class 'str'>
FILTROS SI LOS POSEE
<class 'str'>
VIA DESAGUE
<class 'str'>
ELEMENTOS DE EMPOTRAMIENTO
<class 'float'>
nan
<class 'str'>
DATOS SUMINISTROS COMBUSTIBLE
<class 'str'>
FECHA ULTIMO ABASTECIMIENTO:
<class 'str'>
RELACIÓN RESIDUOS MANTENIMIENTO
<class 'str'>
DESCRIPCION
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'str'>
FOTOS DEL MANTENIMIENTO
<class 'float'>
nan
<class 'str'>
PARA CARGAR FOTOS:  DAR "DOBLE CLICK"
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'str'>
PANÓRAMICA TANQUE ANTES
<class 'float'>
nan
<class 'str'>
PARA CARGAR FOTOS:  DAR "DOBLE CLICK"
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'str'>
PANORÁMICA TANQUE DESPUÉS
<class 'float'>
nan
<class 'str'>
OBSERVACIONES:
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'str'>
SIGA LAS RUTINAS DE MANTENIMIENTO DESCRITAS EN EL PLIEGO.
<class 'float'>
nan
<class 'str'>
ELABORO: NOMBRE:
<class 'str'>
                   POR EL CONTRATISTA
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan
<class 'float'>
nan

In [98]:
df.columns[df.isnull().any()]

Index(['TANQUES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15'],
      dtype='object')

In [68]:
print(df.columns)

Index(['TANQUES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15'],
      dtype='object')

In [99]:
null_columns=df.columns[df.isnull().any()]
df[null_columns].isnull().sum()
print(df[df.isnull().any(axis=1)][null_columns].head())

                                 TANQUES           Unnamed: 1 Unnamed: 2  \
0  SISTEMA DE ALMACENAMIENTO COMBUSTIBLE                  NaN        NaN
1                                    NaN                  NaN        NaN
2                         PERIODICIDAD:                   NaN        NaN
3                                 FECHA:  2020-01-17 00:00:00        NaN
4                                    NaN                  NaN        NaN

  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6    Unnamed: 7 Unnamed: 8  \
0        NaN        NaN        NaN        NaN           NaN        NaN
1        NaN        NaN        NaN        NaN           NaN        NaN
2        NaN        NaN        NaN        NaN           NaN        NaN
3        NaN        NaN        NaN        NaN  HORA INICIO:        NaN
4        NaN        NaN        NaN        NaN           NaN        NaN

                 Unnamed: 9  Unnamed: 10  Unnamed: 11          Unnamed: 12  \
0                       NaN          NaN  TIQUETE OT:                  NaN
1                       NaN          NaN          NaN                  NaN
2  FECHA ULTIMA INSPECCION:          NaN          NaN  2019-08-30 00:00:00
3                  09:30:00  HORA FINAL:          NaN    16:00:00:00 p. m.
4                LOCALIDAD:  NECHI GD211          NaN                  NaN

  Unnamed: 13 Unnamed: 14  Unnamed: 15
0     5184618         NaN          NaN
1         NaN         NaN          NaN
2         NaN         NaN          NaN
3         NaN         NaN          NaN
4         NaN         NaN          NaN

In [34]:
null_columns=df.columns[df.isnull().any()]
df[null_columns].isnull().sum()
df[df.isnull().any(axis=1)][null_columns].head(15)
#print(df[df.isnull().any(axis=1)][null_columns].head(50))

,TANQUES,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,SISTEMA DE ALMACENAMIENTO COMBUSTIBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIQUETE OT:,NaN,5184618,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PERIODICIDAD:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FECHA ULTIMA INSPECCION:,NaN,NaN,2019-08-30 00:00:00,NaN,NaN,NaN
3,FECHA:,2020-01-17 00:00:00,NaN,NaN,NaN,NaN,NaN,HORA INICIO:,NaN,09:30:00,HORA FINAL:,NaN,16:00:00:00 p. m.,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LOCALIDAD:,NECHI GD211,NaN,NaN,NaN,NaN,NaN
5,DATOS TECNICOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MODELO TANQUE,CANT ACPM,NaN,TIPO,NaN,NaN,DIMENSIONES (cm),NaN,NaN,NaN,ALARMA BAJO NIVEL ACPM,NaN,MEDICIÓN NIVEL ACPM,NaN,NaN,NaN
7,NaN,Cap\n(Gls),Existe\n(Gal),Cilindro Vert.,Cilindro Hori.,Cúbico,Diámetro,Alto,Ancho,Largo,EN SITIO (SI/NO),EN GESTIÓN (SI/NO),Visual,Análogo,Digital,NaN
8,Subase,120,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Reserva 1,250,250,1,NaN,NaN,NaN,NaN,NaN,NaN,OK,NaN,OK,NaN,NaN,NaN
10,Reserva 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Reserva 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,TOTAL,370,370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,INTERVENCION,NaN,NaN,LIMPIEZA,NaN,CAMBIO,NaN,OBSERVACIONES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CUERPO EXTERNO,NaN,NaN,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN