In [189]:
import os
import os.path
import shutil
import sys
import glob
from os import remove
from shutil import rmtree

import pandas as pd # cargamos la libreria pandas

In [190]:
source = '/home/infinity/Documentos/Carpeta sin título'
destination = '/home/infinity/Documentos/Carpeta sin título/practica'
carpt = 0

In [191]:
while not os.path.exists(source):
    source = input('Enter a valid source directory\n')
while not os.path.exists(destination):
    destination = input('Enter a valid destination directory\n')

In [192]:
source =  source
print(source)
print(destination)

/home/infinity/Documentos/Carpeta sin título
/home/infinity/Documentos/Carpeta sin título/practica

In [193]:
for f in glob.glob("*EX*.xlsx"):
    print(f)

In [242]:
carpt = 0
for root, dirs, files in os.walk(source, topdown=False):
    for file in files: 
        extension = os.path.splitext(file)[0][0:5].upper()
        #print(file) 
        if extension == "MP_EX":
            print(file)
            df = pd.read_excel(os.path.join(root,file), sheet_name='TANQUE')
            print(df.shape)
           # ruta = '"'+ os.path.join(root,file).upper()+ '"'
           
            #print(os.path.join(root,file))
            #df = pd.read_csv(ruta, decimal='.', encoding='utf-8', header=0)
            #df.shape
            carpt +=   1
        
        
    #rmtree(os.path.join(root))
    
print("PROCESO TERMINADO..OK  TOTAL CARPETAS: " + str(carpt ) )

MP_EX_31012_Universidad Ideas_4628178.xlsx
(98, 16383)
MP_EX_Santa_ana_Oriental_4628645.xlsx
(98, 16383)
MP_EX_MULTIPLAZA INDOOR.xlsx
(98, 16383)
MP_EX_Estacion 11076 - EDIFICIO ARGOS_4628791.xlsx
(98, 16383)
MP_EX_CENTRO INDUSTRIAL BOGOTA_4626638.xlsx
(98, 16383)
MP_EX_LA CALERA_4626940.xlsx
(100, 16383)
MP_EX_FLORENCIA_BOGOTÁ_4628401.xlsx
(98, 16383)
MP_EX_LA CABRERA_4627807.xlsx
(98, 16383)
MP_EX_UGI BOGOTA_4627207.xlsx
(98, 16383)
PROCESO TERMINADO..OK  TOTAL CARPETAS: 9

In [243]:
df.head()

,FORMATO MANTENIMIENTO PREVENTIVO EQUIPOS DE ENERGIA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16373,Unnamed: 16374,Unnamed: 16375,Unnamed: 16376,Unnamed: 16377,Unnamed: 16378,Unnamed: 16379,Unnamed: 16380,Unnamed: 16381,Unnamed: 16382
0,Gerencia Operaciones Campo /Jefatura Operación...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MODELO TANQUE,CANT ACPM,NaN,TIPO,NaN,NaN,DIMENSIONES (cm),NaN,NaN,NaN
1,Código: RED-FT-0104020106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Alto,Ancho,Cap\n(Gls),Diámetro,Existe\n(Gal),Cilindro Vert.,Cilindro Hori.,Cúbico,Largo
2,PLAN DE MANTENIMIENTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Subase,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TANQUES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Reserva 1,NaN,NaN,45,NaN,NaN,NaN,NaN,NaN,NaN
4,SISTEMA DE ALMACENAMIENTO COMBUSTIBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Reserva 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [244]:
df.isnull().values.any()

True

In [245]:
df.isnull().any()

FORMATO MANTENIMIENTO PREVENTIVO EQUIPOS DE ENERGIA    True
Unnamed: 1                                             True
Unnamed: 2                                             True
Unnamed: 3                                             True
Unnamed: 4                                             True
                                                       ...
Unnamed: 16378                                         True
Unnamed: 16379                                         True
Unnamed: 16380                                         True
Unnamed: 16381                                         True
Unnamed: 16382                                         True
Length: 16383, dtype: bool

In [246]:
df.isnull().sum()

FORMATO MANTENIMIENTO PREVENTIVO EQUIPOS DE ENERGIA    58
Unnamed: 1                                             91
Unnamed: 2                                             95
Unnamed: 3                                             94
Unnamed: 4                                             92
                                                       ..
Unnamed: 16378                                         95
Unnamed: 16379                                         96
Unnamed: 16380                                         97
Unnamed: 16381                                         97
Unnamed: 16382                                         97
Length: 16383, dtype: int64

In [247]:
df.isnull().sum().sum()

1605396

In [248]:
nan_rows = df[df.isnull().any(1)]

In [249]:
df.columns[df.isnull().any()]

Index(['FORMATO MANTENIMIENTO PREVENTIVO EQUIPOS DE ENERGIA', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 16373', 'Unnamed: 16374', 'Unnamed: 16375', 'Unnamed: 16376',
       'Unnamed: 16377', 'Unnamed: 16378', 'Unnamed: 16379', 'Unnamed: 16380',
       'Unnamed: 16381', 'Unnamed: 16382'],
      dtype='object', length=16383)

In [254]:
null_columns=df.columns[df.isnull().any()]
df[null_columns].isnull().sum()
print(df[df.isnull().any(axis=1)][null_columns].head(50))

   FORMATO MANTENIMIENTO PREVENTIVO EQUIPOS DE ENERGIA           Unnamed: 1  \
0   Gerencia Operaciones Campo /Jefatura Operación...                   NaN
1                           Código: RED-FT-0104020106                   NaN
2                               PLAN DE MANTENIMIENTO                   NaN
3                                             TANQUES                   NaN
4               SISTEMA DE ALMACENAMIENTO COMBUSTIBLE                   NaN
5                                                 NaN                   NaN
6                                      PERIODICIDAD:                    NaN
7                                              FECHA:   2019-04-15 00:00:00
8                                                 NaN                   NaN
9                                      DATOS TECNICOS                   NaN
10                                      MODELO TANQUE             CANT ACPM
11                                                NaN            Cap\n(Gls)
12                                             Subase                   NaN
13                                          Reserva 1                    45
14                                          Reserva 2                   NaN
15                                          Reserva 3                    80
16                                              TOTAL                   125
17                                       INTERVENCION                   NaN
18                                     CUERPO EXTERNO                   NaN
19                     MANGUERAS INDICADORAS DE NIVEL                   NaN
20                               INDICADORES DE NIVEL                   NaN
21                        MANGUERAS DE ABASTECIMIENTO                   NaN
22                                              FUGAS                   NaN
23                           LLAVES DE ABASTECIMINETO                   NaN
24                                FUGAS EN LAS LLAVES                   NaN
25                                     ENTORNO FISICO                   NaN
26                                           EXTINTOR                   NaN
27                               FILTROS SI LOS POSEE                   NaN
28                                        VIA DESAGUE                   NaN
29                         ELEMENTOS DE EMPOTRAMIENTO                   NaN
30                                                NaN                   NaN
31                      DATOS SUMINISTROS COMBUSTIBLE                   NaN
32                       FECHA ULTIMO ABASTECIMIENTO:                   NaN
33                    RELACIÓN RESIDUOS MANTENIMIENTO                   NaN
34                                        DESCRIPCION                   NaN
35                                                NaN                   NaN
36                                                NaN                   NaN
37                                                NaN                   NaN
38                                                NaN                   NaN
39                            FOTOS DEL MANTENIMIENTO                   NaN
40                                                NaN                   NaN
41              PARA CARGAR FOTOS:  DAR "DOBLE CLICK"                   NaN
42                                                NaN                   NaN
43                                                NaN                   NaN
44                                                NaN                   NaN
45                                                NaN                   NaN
46                                                NaN                   NaN
47                                                NaN                   NaN
48                                                NaN                   NaN
49                                                NaN                   NaN

       Unnamed: 2      Unnamed: 3                             Unnamed: 4  \
0             NaN             NaN                                    NaN
1             NaN             NaN                                    NaN
2             NaN             NaN                                    NaN
3             NaN             NaN                                    NaN
4             NaN             NaN                                    NaN
5             NaN             NaN                                    NaN
6             NaN             NaN                                    NaN
7             NaN             NaN                                    NaN
8             NaN             NaN                                    NaN
9             NaN             NaN                                    NaN
10            NaN            TIPO                                    NaN
11  Existe\n(Gal)  Cilindro Vert.                         Cilindro Hori.
12            NaN             NaN                                    NaN
13            NaN             NaN                                    NaN
14            NaN             NaN                                    NaN
15             12             NaN                                    NaN
16             12             NaN                                    NaN
17            NaN        LIMPIEZA                                    NaN
18            NaN             NaN                                    NaN
19            NaN             NaN                                    NaN
20            NaN             NaN                                    NaN
21            NaN             NaN                                    NaN
22            NaN             NaN                                    NaN
23            NaN             NaN                                    NaN
24            NaN             NaN                                    NaN
25            NaN             NaN                                    NaN
26            NaN             NaN                                    NaN
27            NaN             NaN                                    NaN
28            NaN             NaN                                    NaN
29            NaN             NaN                                    NaN
30            NaN             NaN                                    NaN
31            NaN             NaN                                    NaN
32            NaN             NaN                                    NaN
33            NaN             NaN                                    NaN
34            NaN          UNIDAD                               CANTIDAD
35            NaN             NaN                                    NaN
36            NaN             NaN                                    NaN
37            NaN             NaN                                    NaN
38            NaN             NaN                                    NaN
39            NaN             NaN                                    NaN
40            NaN             NaN                                    NaN
41            NaN             NaN  PARA CARGAR FOTOS:  DAR "DOBLE CLICK"
42            NaN             NaN                                    NaN
43            NaN             NaN                                    NaN
44            NaN             NaN                                    NaN
45            NaN             NaN                                    NaN
46            NaN             NaN                                    NaN
47            NaN             NaN                                    NaN
48            NaN             NaN                                    NaN
49            NaN             NaN                                    NaN

                  Unnamed: 5        Unnamed: 6     Unnamed: 7 Unnamed: 8  \
0                        NaN               NaN            NaN        NaN
1                        NaN               NaN            NaN        NaN
2                        NaN               NaN            NaN        NaN
3                        NaN               NaN            NaN        NaN
4                        NaN               NaN            NaN        NaN
5                        NaN               NaN            NaN        NaN
6                        NaN               NaN            NaN        NaN
7                        NaN               NaN   HORA INICIO:        NaN
8                        NaN               NaN            NaN        NaN
9                        NaN               NaN            NaN        NaN
10                       NaN  DIMENSIONES (cm)            NaN        NaN
11                    Cúbico          Diámetro           Alto      Ancho
12                       NaN               NaN            NaN        NaN
13                       NaN               NaN            NaN        NaN
14                       NaN               NaN            NaN        NaN
15                       NaN               NaN            NaN        NaN
16                       NaN               NaN            NaN        NaN
17                    CAMBIO               NaN  OBSERVACIONES        NaN
18                       NaN               NaN            NaN        NaN
19                       NaN               NaN            NaN        NaN
20                       NaN               NaN            NaN        NaN
21                       NaN               NaN            NaN        NaN
22                       NaN               NaN            NaN        NaN
23                       NaN               NaN            NaN        NaN
24                       NaN               NaN            NaN        NaN
25                       NaN               NaN            NaN        NaN
26                       NaN               NaN            NaN        NaN
27                       NaN               NaN            NaN        NaN
28                       NaN               NaN            NaN        NaN
29                       NaN               NaN            NaN        NaN
30                       NaN               NaN            NaN        NaN
31                       NaN               NaN            NaN        NaN
32  CANTIDAD RECIBIDA (GLS):               NaN            NaN        NaN
33                       NaN               NaN            NaN        NaN
34                       NaN        REFERENCIA            NaN        NaN
35                       NaN               NaN            NaN        NaN
36                       NaN               NaN            NaN        NaN
37                       NaN               NaN            NaN        NaN
38                       NaN               NaN            NaN        NaN
39                       NaN               NaN            NaN        NaN
40                       NaN               NaN            NaN        NaN
41                       NaN               NaN            NaN        NaN
42                       NaN               NaN            NaN        NaN
43                       NaN               NaN            NaN        NaN
44                       NaN               NaN            NaN        NaN
45                       NaN               NaN            NaN        NaN
46                       NaN               NaN            NaN        NaN
47                       NaN               NaN            NaN        NaN
48                       NaN               NaN            NaN        NaN
49                       NaN               NaN            NaN        NaN

                          Unnamed: 9  ... Unnamed: 16373  \
0                                NaN  ...  MODELO TANQUE
1                                NaN  ...            NaN
2                                NaN  ...         Subase
3                                NaN  ...      Reserva 1
4                                NaN  ...      Reserva 2
5                                NaN  ...      Reserva 3
6           FECHA ULTIMA INSPECCION:  ...            NaN
7                           09:00:00  ...            NaN
8                         LOCALIDAD:  ...            NaN
9                                NaN  ...              1
10                               NaN  ...              2
11                             Largo  ...              3
12                               NaN  ...              4
13                               NaN  ...              5
14                               NaN  ...            NaN
15                               NaN  ...            NaN
16                               NaN  ...            NaN
17                               NaN  ...            NaN
18                               NaN  ...            NaN
19                               NaN  ...            NaN
20                               NaN  ...            NaN
21                               NaN  ...            NaN
22                               NaN  ...            NaN
23                               NaN  ...            NaN
24                               NaN  ...            NaN
25                               NaN  ...            NaN
26                               NaN  ...            NaN
27                               NaN  ...            NaN
28                               NaN  ...            NaN
29                               NaN  ...            NaN
30                               NaN  ...            NaN
31                               NaN  ...            NaN
32  PROXIMO ABASTECIMIENTO ESTIMADO:  ...            NaN
33                               NaN  ...            NaN
34                     OBSERVACIONES  ...            NaN
35                               NaN  ...            NaN
36                               NaN  ...            NaN
37                               NaN  ...            NaN
38                               NaN  ...            NaN
39                               NaN  ...            NaN
40                               NaN  ...            NaN
41                               NaN  ...            NaN
42                               NaN  ...            NaN
43                               NaN  ...            NaN
44                               NaN  ...            NaN
45                               NaN  ...            NaN
46                               NaN  ...            NaN
47                               NaN  ...            NaN
48                               NaN  ...            NaN
49                               NaN  ...            NaN

                     Unnamed: 16374 Unnamed: 16375 Unnamed: 16376  \
0                         CANT ACPM            NaN           TIPO
1                              Alto          Ancho     Cap\n(Gls)
2                               NaN            NaN            NaN
3                               NaN            NaN             45
4                               NaN            NaN            NaN
5                               NaN            NaN             80
6                               NaN            NaN            NaN
7                               NaN            NaN            NaN
8                               NaN              1              2
9                     ALTURA_TANQUE            NaN            NaN
10                     ANCHO_TANQUE            NaN            NaN
11                 CAPACIDAD TANQUE             45             80
12            CIRCUNFERENCIA_TANQUE            NaN            NaN
13  VOLUMEN ACTUAL COMBUSTIBLE (GL)            NaN             12
14                              NaN            NaN            NaN
15                              NaN            NaN            NaN
16                              NaN            NaN            NaN
17                              NaN            NaN            NaN
18                              NaN            NaN            NaN
19                              NaN            NaN            NaN
20                              NaN            NaN            NaN
21                              NaN            NaN            NaN
22                              NaN            NaN            NaN
23                              NaN            NaN            NaN
24                              NaN            NaN            NaN
25                              NaN            NaN            NaN
26                              NaN            NaN            NaN
27                              NaN            NaN            NaN
28                              NaN            NaN            NaN
29                              NaN            NaN            NaN
30                              NaN            NaN            NaN
31                              NaN            NaN            NaN
32                              NaN            NaN            NaN
33                              NaN            NaN            NaN
34                              NaN            NaN            NaN
35                              NaN            NaN            NaN
36                              NaN            NaN            NaN
37                              NaN            NaN            NaN
38                              NaN            NaN            NaN
39                              NaN            NaN            NaN
40                              NaN            NaN            NaN
41                              NaN            NaN            NaN
42                              NaN            NaN            NaN
43                              NaN            NaN            NaN
44                              NaN            NaN            NaN
45                              NaN            NaN            NaN
46                              NaN            NaN            NaN
47                              NaN            NaN            NaN
48                              NaN            NaN            NaN
49                              NaN            NaN            NaN

   Unnamed: 16377  Unnamed: 16378    Unnamed: 16379  Unnamed: 16380  \
0             NaN             NaN  DIMENSIONES (cm)             NaN
1        Diámetro   Existe\n(Gal)    Cilindro Vert.  Cilindro Hori.
2             NaN             NaN               NaN             NaN
3             NaN             NaN               NaN             NaN
4             NaN             NaN               NaN             NaN
5             NaN              12               NaN             NaN
6             NaN             NaN               NaN             NaN
7             NaN             NaN               NaN             NaN
8               3               4               NaN             NaN
9             NaN             NaN               NaN             NaN
10            NaN             NaN               NaN             NaN
11            NaN             NaN               NaN             NaN
12            NaN             NaN               NaN             NaN
13            NaN             NaN               NaN             NaN
14            NaN             NaN               NaN             NaN
15            NaN             NaN               NaN             NaN
16            NaN             NaN               NaN             NaN
17            NaN             NaN               NaN             NaN
18            NaN             NaN               NaN             NaN
19            NaN             NaN               NaN             NaN
20            NaN             NaN               NaN             NaN
21            NaN             NaN               NaN             NaN
22            NaN             NaN               NaN             NaN
23            NaN             NaN               NaN             NaN
24            NaN             NaN               NaN             NaN
25            NaN             NaN               NaN             NaN
26            NaN             NaN               NaN             NaN
27            NaN             NaN               NaN             NaN
28            NaN             NaN               NaN             NaN
29            NaN             NaN               NaN             NaN
30            NaN             NaN               NaN             NaN
31            NaN             NaN               NaN             NaN
32            NaN             NaN               NaN             NaN
33            NaN             NaN               NaN             NaN

In [267]:
df[10:18]

,FORMATO MANTENIMIENTO PREVENTIVO EQUIPOS DE ENERGIA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16373,Unnamed: 16374,Unnamed: 16375,Unnamed: 16376,Unnamed: 16377,Unnamed: 16378,Unnamed: 16379,Unnamed: 16380,Unnamed: 16381,Unnamed: 16382
10,MODELO TANQUE,CANT ACPM,NaN,TIPO,NaN,NaN,DIMENSIONES (cm),NaN,NaN,NaN,...,2,ANCHO_TANQUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Cap\n(Gls),Existe\n(Gal),Cilindro Vert.,Cilindro Hori.,Cúbico,Diámetro,Alto,Ancho,Largo,...,3,CAPACIDAD TANQUE,45,80,NaN,NaN,NaN,NaN,NaN,NaN
12,Subase,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,CIRCUNFERENCIA_TANQUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Reserva 1,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,VOLUMEN ACTUAL COMBUSTIBLE (GL),NaN,12,NaN,NaN,NaN,NaN,NaN,NaN
14,Reserva 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Reserva 3,80,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,TOTAL,125,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,INTERVENCION,NaN,NaN,LIMPIEZA,NaN,CAMBIO,NaN,OBSERVACIONES,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN